### ISSUE TITLE
Replace home page with another page

### ISSUE THREAD

**Issue by shahroq** [shahroq/whale_c5_cheat_sheet#12]
@mlocati @mnakalay 
Do you think it would be possible to come up with a piece of code that swap a page with the root page using c5 API? 
It should swap all entities linked to a page, including blocks, stacks, areas, attributes, page template/type, versions, etc.

**Comment by mlocati** [comment]
For which concrete5 version?

**Comment by shahroq** [comment]
@mlocati the latest?

**Comment by mlocati** [comment]
Since concrete5 8.5.0 you can use the page cloner class.

For example, when you go to the sitemap page, drag a page over another one, and choose the `Copy Page / Replace "Page 1" with a copy of "Page 2"` option, here's the code that's executed: https://github.com/concrete5/concrete5/blob/8.5.1/concrete/controllers/dialog/page/drag_request.php#L248-L267

(you can use xdebug to see the actual values of the variables)

**Comment by shahroq** [comment]
Fantastic! I haven't noticed this new feature.

**Comment by mlocati** [comment]
The page cloner was introduced by https://github.com/concrete5/concrete5/pull/7207 (and fixed by a couple of other pull requests).

Maybe it was given less emphasis than it deserved: no notes in the [8.5.0 announcement](https://www.concrete5.org/about/blog/core-releases/concrete5-850-now-available) and just a bare "Added the ability to replace a page with another page" on [the release notes](https://documentation.concrete5.org/developers/background/version-history/850-release-notes), where it was somehow hidden because of the ton of changes in 8.5.0...

**Comment by shahroq** [comment]
I have been asked about this many times, as in Pixel there are multiple Home pages, and in many cases, customers intend to use alternative home pages. I was about to provide an option to facilitate the replacement, instead of time-consuming recommended copy/paste procedure.
Much obliged for this feature!
